### ISSUE TITLE
Missing support for embedding into Qiskit

### ISSUE THREAD

**Issue by rsln-s** [CQCL/pytket-quantinuum#65]
Pytket supports embedding pytket backends into Qiskit quantum instances. From documentation: "Each Backend in pytket can be wrapped up to imitate a Qiskit backend".  See https://cqcl.github.io/pytket/manual/manual_backend.html#embedding-into-qiskit

However, pytket-quantinuum does not support that. The following code
```python
from qiskit.utils import QuantumInstance
from pytket.extensions.quantinuum import QuantinuumBackend

backend = QuantinuumBackend(device_name="H1-1E")

qinstance = QuantumInstance(backend)
```
fails with the following error
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [10], line 6
      2 from pytket.extensions.quantinuum import QuantinuumBackend
      4 backend = QuantinuumBackend(device_name="H1-1E")
----> 6 qinstance = QuantumInstance(backend)

File /opt/omniai/work/instance1/jupyter/qcware_env/lib/python3.8/site-packages/qiskit/utils/quantum_instance.py:284, in QuantumInstance.__init__(self, backend, shots, seed_simulator, max_credits, basis_gates, coupling_map, initial_layout, pass_manager, bound_pass_manager, seed_transpiler, optimization_level, backend_options, noise_model, timeout, wait, skip_qobj_validation, measurement_error_mitigation_cls, cals_matrix_refresh_period, measurement_error_mitigation_shots, job_callback, mit_pattern, max_job_retries)
    281 self._run_config = run_config
    283 # setup backend config
--> 284 if self._backend_interface_version <= 1:
    285     basis_gates = basis_gates or backend.configuration().basis_gates
    286     coupling_map = coupling_map or getattr(backend.configuration(), "coupling_map", None)

TypeError: '<=' not supported between instances of 'NoneType' and 'int'
```

Desired behavior: `QuantinuumBackend` should behave like other pytket backends.

Package versions:

```
>> qiskit.__qiskit_version__
{'qiskit-terra': '0.22.0', 'qiskit-aer': '0.11.0', 'qiskit-ignis': None, 'qiskit-ibmq-provider': '0.19.2', 'qiskit': '0.39.0', 'qiskit-nature': None, 'qiskit-finance': None, 'qiskit-optimization': None, 'qiskit-machine-learning': None}
>> pytket.__version__
'1.7.3'
>> pytket.extensions.quantinuum.__extension_version__
0.9.0
```

**Comment by yao-cqc** [comment]
Hi, thanks for posting the issue.

Unfortunately, there are currently two issues: https://github.com/CQCL/pytket-qiskit/issues/15, https://github.com/CQCL/pytket-qiskit/issues/14 that prevent embedding a `QuantinuumBackend` into qiskit . For the time being I would suggest converting a qiskit circuit to a tket circuit using `pytket.extensions.qiskit.qiskit_convert.qiskit_to_tk` and then process that tket circuit directly using a `QuantinuumBackend`.


Regarding your example code, you need to wrap the `Quantinuum` backend inside a `TketBackend` in order to build a valid `QuantumInstance`. This is because the `TketBackend` implements the `qiskit.providers.BaseBackend` class.

For example:
```python
from pytket.extensions.qiskit.tket_backend import TketBackend
from pytket.extensions.quantinuum import QuantinuumBackend
from qiskit.transpiler.passes import Unroller
b = QuantinuumBackend(device_name="H1-1E")
backend = TketBackend(b, b.default_compilation_pass())
pass_ = Unroller(['u1', 'u2', 'u3', 'cx'])
qinstance = QuantumInstance(backend, pass_manager=pass_)
```
Notice that internally qiskit will sometimes compile a circuit that contains a "meta op" (e.g. Grover) into the gateset defined by the `TketBackend` if the `pass_manager` argument isn't set. Since Qiskit doesn't support all the Quantinuum gates you need to pass a custom qiskit pass to the `QuantumInstance`. In this example it's a `Unroller` pass that tells qiskit to rebase everything into 'u1', 'u2', 'u3'.

**Comment by yao-cqc** [comment]
Close this issue since the blockers in ``pytket-qiskit`` have been resolved.
https://github.com/CQCL/pytket-qiskit/issues/15
https://github.com/CQCL/pytket-qiskit/issues/14
